name: Pull Request Logger

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  log_pr_details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log pull request details
        run: |
          echo "Pull Request #$${{ github.event.pull_request.number }} triggered."
          echo "Title: $${{ github.event.pull_request.title }}"
          echo "Status: $${{ github.event.action }}"
          echo "Author: $${{ github.event.pull_request.user.login }}"
          echo "Source Branch: $${{ github.event.pull_request.head.ref }}"
          echo "Target Branch: $${{ github.event.pull_request.base.ref }}"
          echo "URL: $${{ github.event.pull_request.html_url }}"
